@startuml

%getenv('PUML_THEME')

|Frontend|
start

:Get available documents
""GET /"";

|Backend|
:Look up and return
available documents from database;

|Frontend|
while (Documents available?) is (yes)
	:Select document and request list of tokens
	""GET /<docid>/tokens.json"";

	|Backend|
	:Look up document and return
	list of tokens from database;

	|Frontend|
	while (Tokens available?) is (yes)
		:Request token info from server
		""GET /<docid>/token-<index>.json""
		""GET /<docid>/token-<index>.png""
	
		or
	
		""GET /random""
		(redirects to a random token's JSON);
	
		|Backend|
		:Look up and return
		token from database;
	
		|Frontend|
		:Present user with a
		token to evaluate;

		:User chooses;
	
		if (accept)
			:Submit choice to server:
			""POST /<docid>/token-<index>.json""
			with //original// as ""gold"" parameter;
		elseif (correct)
			:Submit choice to server:
			""POST /<docid>/token-<index>.json""
			with //user input// as ""gold"" parameter;
		elseif (hyphenate)
			:Submit choice to server:
			""POST /<docid>/token-<index>.json""
			with //left// or //right// as ""hyphenate"" parameter;
		else (nothing)
			stop
		endif

		|Backend|
		:Write ""gold"" token to database;
	
	endwhile (no)
	'TODO fix arrow
	-[#blue]->
endwhile (no)

|Frontend|
stop

@enduml